CREATE TABLE TB_ZLGOON_SCHEDULER (
	SCHEDULER_NAME			VARCHAR(30) NOT NULL,
	MEMO					VARCHAR(500), 
	TRIGGER_TYPE			VARCHAR(1) NOT NULL DEFAULT 'C',
	TRIGGER_VALUE			VARCHAR(50) NOT NULL,
	POOL_SIZE				INT NOT NULL DEFAULT 1,
	LAST_EXE_DATE			DATETIME,
	RUNNING_TIME			BIGINT,
	RUNNING_STATUS 			VARCHAR(1) NOT NULL DEFAULT 'S',
	JOB_STATUS 				VARCHAR(1) NOT NULL DEFAULT 'S',
	USE_YN 					VARCHAR(1) NOT NULL DEFAULT 'Y',
	REG_DATE				DATETIME NOT NULL,
	REG_ID					VARCHAR(30) NOT NULL,
	MOD_DATE				DATETIME NOT NULL,
	MOD_ID					VARCHAR(30) NOT NULL,
	PRIMARY KEY (SCHEDULER_NAME)
);

CREATE TABLE TB_ZLGOON_SCHEDULER_LOG (
	SCHEDULER_LOG_SEQ		BIGINT NOT NULL,
	SCHEDULER_NAME			VARCHAR(30) NOT NULL,
	START_DATE				DATETIME NOT NULL,
	END_DATE				DATETIME NOT NULL,
	RUNNING_TIME			BIGINT NOT NULL,
	ERROR_YN				VARCHAR(1) NOT NULL DEFAULT 'N',
	REG_DATE				DATETIME NOT NULL,
	
	PRIMARY KEY (SCHEDULER_LOG_SEQ)
);


INSERT INTO TB_ZLGOON_SCHEDULER (SCHEDULER_NAME, TRIGGER_VALUE, REG_DATE, REG_ID, MOD_DATE, MOD_ID)
VALUES ('scheduler1_name', '*/5 * * * * *', sysdate(), 'hosuk.lee', sysdate(), 'hosuk.lee');

INSERT INTO TB_ZLGOON_SCHEDULER (SCHEDULER_NAME, TRIGGER_VALUE, REG_DATE, REG_ID, MOD_DATE, MOD_ID)
VALUES ('scheduler2_name', '*/5 * * * * *', sysdate(), 'hosuk.lee', sysdate(), 'hosuk.lee');
